### ISSUE TITLE
Keyboard not working on mobile

### ISSUE THREAD

**Issue by TheAvacad0** [meower-media-co/Meower-Website#25]
In attempting to do anything that involves typing in mobile, the keyboard won’t show up. The text box just illuminates. I’ve tested this on Safari and DuckDuckGo on iOS 15.

**Comment by JoshAtticus** [comment]
> In attempting to do anything that involves typing in mobile, the keyboard won’t show up. The text box just illuminates. I’ve tested this on Safari and DuckDuckGo on iOS 15.

Hello @TheAvacad0! Could I please get some information on what client you use? app.meower.org and beta.meower.org does not work on mobile, you must use svelte.meower.org.
